{{- if eq .Values.cilium.cluster.name "siliconsheep-home" }}
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium-bgp-policy-home
spec:
  nodeSelector:
    matchLabels:
      k8s.siliconsheep.se/location: "home"
  virtualRouters:
    - localASN: 64513
      neighbors:
        - peerASN: 64512
          peerAddress: 172.27.20.1
      serviceSelector:
        matchLabels:
          bgp.siliconsheep.se/announce: "true"
{{- end }}