{{- if eq .Values.cilium.cluster.name "siliconsheep-home" }}
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-lb-ippool
spec:
  cidrs:
    - cidr: 172.27.120.0/24
{{- end }}