vault-secret-provider:
  enabled: true
  roleName: oauth2-proxy
  defaultObjectPath: auth/oauth2-proxy
  objects:  
    - name: redis-password
    - name: cookie-secret
    - name: domain
      path: auth/oauth-credentials/oauth2-proxy
    - name: client-id
      path: auth/oauth-credentials/oauth2-proxy
    - name: client-secret
      path: auth/oauth-credentials/oauth2-proxy
  secretObjects: true
  secretName: oauth2-proxy-secrets

app-template:
  fullnameOverride: oauth2-proxy

  controller:
    replicas: 2
    strategy: RollingUpdate
  
  serviceAccount:
    create: true

  podAnnotations:
    secret.reloader.stakater.com/reload: oauth2-proxy-secrets

  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.4.0

  env:
    OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
    OAUTH2_PROXY_METRICS_ADDRESS: 0.0.0.0:44180
    OAUTH2_PROXY_COOKIE_DOMAINS: siliconsheep.se
    OAUTH2_PROXY_COOKIE_SECRET:
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-secrets
          key: cookie-secret
    OAUTH2_PROXY_COOKIE_SECURE: true
    OAUTH2_PROXY_EMAIL_DOMAINS: "*"
    OAUTH2_PROXY_SCOPE: "openid profile email"
    OAUTH2_PROXY_PROVIDER: oidc
    OAUTH2_PROXY_OIDC_ISSUER_URL:
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-secrets
          key: domain
    OAUTH2_PROXY_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-secrets
          key: client-id
    OAUTH2_PROXY_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-secrets
          key: client-secret
    # TODO: chage to https://siliconsheep.se/groups once
    # https://github.com/oauth2-proxy/oauth2-proxy/issues/1730 is fixed
    OAUTH2_PROXY_OIDC_GROUPS_CLAIM: https://siliconsheep/groups
    OAUTH2_PROXY_SESSION_STORE_TYPE: redis
    OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://oauth2-proxy-redis:6379
    OAUTH2_PROXY_REDIS_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-secrets
          key: redis-password

    OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: true
    OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
    OAUTH2_PROXY_PASS_USER_HEADERS: true
    OAUTH2_PROXY_PREFER_EMAIL_TO_USER: true
    OAUTH2_PROXY_SET_AUTHORIZATION-HEADER: true
    OAUTH2_PROXY_SET_XAUTHREQUEST: true
    OAUTH2_PROXY_REVERSE_PROXY: true
    OAUTH2_PROXY_WHITELIST_DOMAINS: .siliconsheep.se

  service:
    main:
      ports:
        http:
          port: 4180
        metrics:
          port: 44180
          enabled: true

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "auth2.siliconsheep.se" # TODO: Change to auth.siliconsheep.se
          paths:
            - path: /oauth2
              pathType: Prefix
      tls:
        - hosts: [auth2.siliconsheep.se]
          secretName: auth2-siliconsheep-se

  persistence:
    secrets-fakemount:
      enabled: true
      type: custom
      mountPath: /mnt/secrets-fakemount
      readOnly: true
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true

  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      cpu: 20m
      memory: 105M