vault-secret-provider:
  cluster: home
  enabled: true
  roleName: oauth2-proxy-home
  defaultObjectPath: auth/oauth2-proxy
  objects:  
    - name: redis-password
    - name: cookie-secret
    - name: domain
      path: auth/oauth-credentials/dhome
    - name: client-id
      path: auth/oauth-credentials/dhome
    - name: client-secret
      path: auth/oauth-credentials/dhome
  secretObjects: true
  secretName: oauth2-proxy-secrets

app-template:
  ingress:
    main:
      hosts:
        - host: "auth2.siliconsheep.se"
          paths:
            - path: /oauth2
              pathType: Prefix
      tls:
        - hosts: [auth2.siliconsheep.se]
          secretName: auth2-siliconsheep-se

  persistence:
    secrets-fakemount:
      volumeSpec:
        csi:
          volumeAttributes:
            secretProviderClass: oauth2-proxy-home