external-dns:
  fullnameOverride: external-dns

  image:
    registry: eu.gcr.io
    repository: k8s-artifacts-prod/external-dns/external-dns
    tag: v0.6.0

  provider: cloudflare
  crd:
    create: true
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)