external-dns:
  fullnameOverride: external-dns

  image:
    tag: v0.13.1

  provider: cloudflare
  crd:
    create: true
  
  resources:
    requests:
      cpu: 25m
      memory: 100Mi
    limits:
      memory: 100Mi