external-dns:
  txtOwnerId: oke
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
    - --exclude-target-net=172.28.1.0/27