snapshot-controller:
  volumeSnapshotClasses:
  - name: longhorn-snapshot-vsc
    labels:
        velero.io/csi-volumesnapshot-class: "true"
    driver: driver.longhorn.io
    deletionPolicy: Delete
    parameters:
      type: snap
serviceMonitor:
  create: true