apiVersion: v2
name: snapshot-controller
version: 1.0.0
dependencies:
- name: snapshot-controller
  version: 1.8.3
  repository: https://piraeus.io/helm-charts/
- name: snapshot-validation-webhook
  version: 1.7.4
  repository: https://piraeus.io/helm-charts/