{{- $defaultSecretMountPath := .Values.defaultSecretMountPath -}}
{{- $defaultObjectPath := .Values.spc.defaultObjectPath -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    roleName: {{ .Values.roleName }}
    vaultAddress: {{ .Values.vaultAddress }}
    vaultKubernetesMountPath: {{ printf "kubernetes/%s" (required ".Values.cluster missing" .Values.cluster) }}
    objects: |
      {{- range .Values.objects }}
      - objectName: {{ .name }}
        secretKey: {{ default .name .key }}
        secretPath: {{ printf "%s/data/%s" (default $defaultSecretMountPath .mount) (default $defaultObjectPath .path) }}
      {{- end }}
  {{- if or .Values.secretObjects .Values.extraSecretObjects }}
  secretObjects:
    {{- if .Values.objects }}
    - type: Opaque
      secretName: {{ default .Release.Name .Values.secretName }}
      data:
        {{- range .Values.objects }}
        - key: {{ default .name .secretName }}
          objectName: {{ .name }}
        {{- end }}
    {{- end }}
    {{- with .Values.extraSecretObjects }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}