global:
  fullnameOverride: plex

networkPolicies:
  enabled: false

app-template:
  controller:
    replicas: 1

  image:
    repository: ghcr.io/onedr0p/plex
    tag: 1.41.3.9314-a0bfb8370@sha256:cbefe5f2f44d0519fd72985ed4005b7b55a7eb9dcbdcc3b4d6bb7055730db565

  env:
    TZ: "Europe/Stockholm"
    # cat /config/Library/Application\ Support/Plex\ Media\ Server/Preferences.xml | tr " " "\n" | \
    # sed -n '/<Preferences/,$p' | tail -n +2 | sed 's,/>,,g' | \
    # sed '/\(OldestPreviousVersion\|MachineIdentifier\|^PlexOnline\|Certificate\|PubSub\|NeedsUpdate\)/d' | \
    # sed 's/"//g' | awk '{print "PLEX_PREFERENCE_"i++": \""$0"\""}'
    PLEX_PREFERENCE_0: "allowedNetworks=172.27.10.0/24,172.27.20.0/24"
    PLEX_PREFERENCE_1: "TranscoderTempDirectory=/transcode"
    PLEX_PREFERENCE_2: "FriendlyName=SiliconSheep"
    PLEX_PREFERENCE_3: "HardwareAcceleratedCodecs=1"
    PLEX_PREFERENCE_4: "autoEmptyTrash=1"
    PLEX_PREFERENCE_5: "ManualPortMappingPort=443"
    PLEX_PREFERENCE_6: "ScheduledLibraryUpdateInterval=86400"
    PLEX_PREFERENCE_7: "TranscoderCanOnlyRemuxVideo=0"
    PLEX_PREFERENCE_8: "HardwareAcceleratedEncoders=1"
    PLEX_PREFERENCE_9: "EnableIPv6=0"
    PLEX_PREFERENCE_10: "sendCrashReports=0"
    PLEX_PREFERENCE_11: "DlnaEnabled=0"
    PLEX_PREFERENCE_12: "ManualPortMappingMode=1"
    PLEX_PREFERENCE_13: "ScheduledLibraryUpdatesEnabled=1"
    PLEX_PREFERENCE_14: "CinemaTrailersFromLibrary=0"
    PLEX_PREFERENCE_15: "CinemaTrailersType=1"
    PLEX_PREFERENCE_16: "MetricsEpoch=1"
    PLEX_PREFERENCE_17: "AcceptedEULA=1"
    PLEX_PREFERENCE_18: "PublishServerOnPlexOnlineKey=1"
    PLEX_PREFERENCE_19: "DvrIncrementalEpgLoader=0"
    PLEX_PREFERENCE_20: "LastAutomaticMappedPort=0"
    PLEX_PREFERENCE_21: "DisableTLSv1_0=1"
    PLEX_PREFERENCE_22: "RelayEnabled=0"
    PLEX_PREFERENCE_23: "TreatWanIpAsLocal=0"
    PLEX_PREFERENCE_24: "customConnections=https://plex.siliconsheep.se"
    PLEX_PREFERENCE_25: "LanguageInCloud=1"
    PLEX_PREFERENCE_26: "GdmEnabled=0"
    PLEX_PREFERENCE_27: "secureConnections=2"
    PLEX_PREFERENCE_28: "TranscoderToneMapping=0"
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 20Gi
    transcode:
      enabled: true
      type: emptyDir
      mountPoint: /transcode
    media:
      enabled: true
      type: nfs
      server: "nas.siliconsheep.se"
      path: /volume1/media/
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 100
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /identity
          port: 32400
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 1
        failureThreshold: 3
    readiness:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /identity
          port: 32400
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 1
        failureThreshold: 3
  resources:
    requests:
      gpu.intel.com/i915: 1
      cpu: 100m
      memory: 2Gi
    limits:
      gpu.intel.com/i915: 1
      memory: 4Gi

  service:
    main:
      ports:
        http:
          port: 32400

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "plex.siliconsheep.se"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-siliconsheep-se
          hosts:
            - "plex.siliconsheep.se"
