# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: google-prod
# spec:
#   acme:
#     email: xxxx
#     server: https://dv.acme-v02.api.pki.goog/directory
#     externalAccountBinding:
#       keyID: xxxx
#       keySecretRef:
#         name: cert-manager-google
#         key: eab-secret
#       keyAlgorithm: HS256
#     privateKeySecretRef:
#       name: google-prod
#     solvers:
#     - dns01:
#         cloudflare:
#           apiTokenSecretRef:
#             name: cloudflare-api-token
#             key: api-token