global:
  domain: siliconsheep.se
  cluster: ""

traefik:
  fullnameOverride: traefik

  globalArguments:
    - "--serverstransport.insecureskipverify=true"
    # - "--entrypoints.websecure.http.middlewares=ingress-error-pages@kubernetescrd"

  deployment:
    annotations:
      reloader.stakater.com/match: "true"

  autoscaling:
    enabled: true
    metrics:
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80

  logs:
    general:
      format: json
      level: ERROR
    access:
      enabled: true
      format: json

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesIngress:
      publishedService:
        enabled: true

  ports:
    web:
      redirectTo: websecure
    websecure:
      tls:
        enabled: true

  service:
    spec:
      externalTrafficPolicy: Local

  experimental:
    plugins:
      enabled: true
  
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: 'app.kubernetes.io/name'
                  operator: In
                  values:
                    - traefik
            topologyKey: 'kubernetes.io/hostname'