- name: cert-manager
  namespace: networking
  valueFiles:
  - base.yaml
# - monitoring.yaml # Requires Prometheus
- name: external-dns
  namespace: networking
  valueFiles:
  - base.yaml
  - values-oke.yaml
# - monitoring.yaml # Requires Prometheus
- name: metrics-server
  namespace: monitoring
  valueFiles:
  - base.yaml
# - monitoring.yaml # Requires Prometheus
- name: traefik
  namespace: ingress
  valueFiles:
  - base.yaml # Requires Cert-manager
  - values-oke.yaml
# - monitoring.yaml # Requires Prometheus
- name: traefik-error-pages
  namespace: ingress
  valueFiles:
  - base.yaml # Requires Traefik
  - values-oke.yaml
- name: secrets-store-csi-driver
  namespace: kube-system
  valueFiles:
  - base.yaml
- name: vault
  valueFiles:
  - base.yaml # Requires Traefik
- name: longhorn
  namespace: longhorn-system
  valueFiles:
  - base.yaml
  - values-oke.yaml