- name: cert-manager
  valueFiles:
  - base.yaml
# - monitoring.yaml # Requires Prometheus
- name: external-dns
  valueFiles:
  - base.yaml
  - values-oke.yaml
# - monitoring.yaml # Requires Prometheus
- name: metrics-server
  valueFiles:
  - base.yaml
# - monitoring.yaml # Requires Prometheus
- name: traefik
  valueFiles:
  - base.yaml # Requires Cert-manager
  - values-oke.yaml
# - monitoring.yaml # Requires Prometheus