- name: cert-manager
  valueFiles:
  - base.yaml
# - monitoring.yaml # Requires Prometheus
- name: external-dns
  valueFiles:
  - base.yaml
  - values-oke.yaml
# - monitoring.yaml # Requires Prometheus