- name: cert-manager
  namespace: networking
  valueFiles:
  - base.yaml
  - monitoring.yaml # Requires Prometheus
- name: external-dns
  namespace: networking
  valueFiles:
  - base.yaml
  - values-oke.yaml
- name: metrics-server
  namespace: monitoring
  valueFiles:
  - base.yaml
  - monitoring.yaml # Requires Prometheus
- name: ingress-nginx
  namespace: ingress
  valueFiles:
  - base.yaml
  - values-oke.yaml
  - monitoring.yaml # Requires Prometheus
- name: secrets-store-csi-driver
  namespace: kube-system
  valueFiles:
  - base.yaml
- name: vault
  valueFiles:
  - base.yaml # Requires Traefik
- name: oauth2-proxy
  namespace: auth
  valueFiles:
  - base.yaml
  - values-oke.yaml
- name: oauth2-proxy-redis
  namespace: auth
  valueFiles:
  - base.yaml
  - values-oke.yaml
- name: prometheus
  namespace: monitoring
  serverSideApply: true
  rawHelm: "yes"
  valueFiles:
  - base.yaml
  - values-oke.yaml
  - "/infra-vars/values-prometheus.yaml"
- name: argocd
  valueFiles:
  - base.yaml
- name: argocd-appset
  namespace: argocd
  valueFiles:
  - base.yaml
- name: vpa
  namespace: monitoring
  valueFiles:
  - base.yaml
- name: goldilocks
  namespace: monitoring
  valueFiles:
  - base.yaml
- name: echoserver
  namespace: default
  valueFiles:
  - base.yaml
  - values-oke.yaml
- name: cluster-autoscaler
  namespace: kube-system
  rawHelm: "yes"
  valueFiles:
  - base.yaml
  - "/infra-vars/values-cluster-autoscaler.yaml"