# - name: cert-manager # Requires Vault
#   valueFiles:
#   - base.yaml
#   - monitoring.yaml # Requires Prometheus
# - name: external-dns # Requires Vault
#   valueFiles:
#   - base.yaml
#   - values-home.yaml
#   - monitoring.yaml # Requires Prometheus
# - name: metrics-server
#   valueFiles:
#   - base.yaml
#   - monitoring.yaml # Requires Prometheus
# - name: traefik
#   valueFiles:
#   - base.yaml # Requires Cert-manager
#   - values-home.yaml
#   - monitoring.yaml # Requires Prometheus
# - name: traefik-error-pages
#   valueFiles:
#   - base.yaml # Requires Traefik
#   - values-home.yaml
- name: secrets-store-csi-driver
  valueFiles:
  - base.yaml
# - name: vault
#   valueFiles:
#   - base.yaml # Requires Traefik
# - name: longhorn
#   namespace: longhorn-system
#   valueFiles:
#   - base.yaml
#   - values-home.yaml