apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: 0 4 * 1 *
  useOwnerReferencesInBackup: false
  template:
    storageLocation: scaleway-primary
    hooks: {}
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    includeClusterResources: true
    metadata:
      labels:
        type: 'full'
        schedule: 'daily'
    ttl: 360h0m0s