vault-secret-provider:
  enabled: true
  roleName: oauth2-proxy
  defaultObjectPath: auth/oauth2-proxy
  objects:  
    - name: REDIS_PASSWORD
      key: redis-password
  secretObjects: true
  secretName: oauth2-proxy-secrets-redis

app-template:
  fullnameOverride: oauth2-proxy-redis

  controller:
    strategy: RollingUpdate
  
  serviceAccount:
    create: true

  image:
    repository: public.ecr.aws/docker/library/redis
    tag: 7.2.1@sha256:ae51486efeea8a9b3f85542e408f79a5012d5b7fa35ae19733104ecc6992a248

  podAnnotations:
    secret.reloader.stakater.com/reload: oauth2-proxy-secrets

  command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]

  env:
    REDIS_REPLICATION_MODE: master

  envFrom:
    - secretRef:
        name: oauth2-proxy-secrets-redis

  service:
    main:
      ports:
        http:
          enabled: false
        redis:
          enabled: true
          port: 6379

  persistence:
    secrets-fakemount:
      enabled: true
      type: custom
      mountPath: /mnt/secrets-fakemount
      readOnly: true
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true

  resources:
    requests:
      cpu: 15m
      memory: 64M
    limits:
      memory: 128M