name: oauth2-proxy-redis
apiVersion: v2
version: 1.0.0
dependencies:
  - name: app-template
    version: 2.6.0
    repository: https://bjw-s.github.io/helm-charts/
  - name: vault-secret-provider
    version: 1.0.0
    repository: file://../partial/vault-secret-provider
    condition: vault-secret-provider.enabled