vault-secret-provider:
  cluster: home

app-template:
  persistence:
    secrets-fakemount:
      volumeSpec:
        csi:
          volumeAttributes:
            secretProviderClass: oauth2-proxy-redis-home