global:
  cluster: oke

ingress-nginx:
  controller:
    autoscaling:
      minReplicas: 1
      maxReplicas: 2

    service:
      annotations:
        reloader.stakater.com/match: "true"
        oci.oraclecloud.com/load-balancer-type: "nlb"
    
    ingressClassResource:
      default: true
  
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        memory: "512Mi"