ingress-nginx:
  controller:
    autoscaling:
      minReplicas: 2
      maxReplicas: 5

    service:
      loadBalancerIP: "172.27.120.1"

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi