global:
  cluster: oke

ingress-nginx:
  controller:
    autoscaling:
      minReplicas: 1
      maxReplicas: 2

    service:
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
    
    # TODO: remove once Traefik is gone
    ingressClassResource:
      default: false
  
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        memory: "512Mi"