global:
  cluster: home

ingress-nginx:
  controller:
    autoscaling:
      minReplicas: 2
      maxReplicas: 5

    service:
      labels:
        bgp.siliconsheep.se/announce: "true"
      annotations:
        reloader.stakater.com/match: "true"
        io.cilium/lb-ipam-ips: "172.27.120.1"
    
    publishService:
      pathOverride: "ingress/ingress-expose"

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi