{{- if .Values.networkPolicies.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: radarr
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: ingress-nginx-home
            app.kubernetes.io/name: ingress-nginx
            io.kubernetes.pod.namespace: ingress
      toPorts:
        - ports:
            - port: "7878"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchPattern: "*"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
          rules:
            http: 
            - {}
    - toServices:
        - k8sService:
            serviceName: plex
            namespace: media
      toPorts:
        - ports:
            - port: "32400"
              protocol: TCP
          rules:
            http: 
            - {}
    - toServices:
        - k8sService:
            serviceName: sabnzbd
            namespace: media
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
          rules:
            http: 
            - {}
{{- end }}
