goldilocks:
  controller:
    resources:
      requests:
        cpu: 10m
        memory: 64M
      limits:
        memory: 250M
  dashboard:
    replicaCount: 1
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-url: https://auth.siliconsheep.se/oauth2/auth?allowed_groups=admins
        nginx.ingress.kubernetes.io/auth-signin: https://auth.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: goldilocks.siliconsheep.se
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: goldilocks-siliconsheep-se
          hosts:
            - goldilocks.siliconsheep.se
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 100M