apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ template "authentik.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "authentik.fullname" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: "Postgres database for Authentik"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.0
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: {{ .Values.postgres.secretName }}

  postgresql:
    parameters:
      password_encryption: md5
    pg_hba:
      - host all all all md5

  storage:
    storageClass: {{ .Values.postgres.storageClassName }}
    size: {{ .Values.postgres.storageSize }}

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi