# TODO: Fix Authentik(-remote-cluster) Helm chart upstream to properly honor nameOverride
# In the meantime, just create a second ServiceAccount with the correct name 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" (dict "Chart" .Chart "Values" .Values.authentik) }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.authentik.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}