vault:
  server:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: vault.siliconsheep.se
          paths: [/]
      tls:
        - hosts: [vault.siliconsheep.se]
          secretName: vault-siliconsheep-se
    
    extraSecretEnvironmentVars:
      - envName: VAULT_OCIKMS_SEAL_KEY_ID
        secretName: vault-oci-kms
        secretKey: kms_key_id
      - envName: VAULT_OCIKMS_CRYPTO_ENDPOINT
        secretName: vault-oci-kms
        secretKey: crypto_endpoint
      - envName: VAULT_OCIKMS_MANAGEMENT_ENDPOINT
        secretName: vault-oci-kms
        secretKey: management_endpoint
  
    dataStorage:
      enabled: false

    standalone:
      enabled: false
    
    ha:
      enabled: true
      replicas: 3
      config: |
        ui = true

        storage "oci" {
          namespace_name = "axgjp2y2qkbb"
          bucket_name = "vault-backend"
          ha_enabled = "true"
          lock_bucket_name = "vault-backend-lock"
        }

        seal "ocikms" {}

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        service_registration "kubernetes" {}

  ui:
    enabled: true
  
  csi:
    enabled: true
  
  injector:
    enabled: false
