vault:
  server:
    # image:
    #   repository: "vault"
    #   tag: "1.12.0"
    #   pullPolicy: IfNotPresent
    ingress:
      enabled: true
      pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: vault.siliconsheep.se
          paths: [/]
      tls:
        - hosts: [vault.siliconsheep.se]
          secretName: vault-siliconsheep-se
  
  dataStorage:
    storageClass: oci

  standalone:
    config: |
      storage "oci" {
        namespace_name = "axgjp2y2qkbb"
        bucket_name = "vault-backend"
      }

  ui:
    enabled: true
  
  csi:
    enabled: true
  
  injector:
    enabled: false
