vault:
  server:
    ingress:
      enabled: true
      pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: vault.siliconsheep.se
          paths: [/]
      tls:
        - hosts: [vault.siliconsheep.se]
          secretName: vault-siliconsheep-se
  
    dataStorage:
      enabled: false

    standalone:
      enabled: false
    
    ha:
      enabled: true
      replicas: 3
      config: |
        ui = true

        storage "oci" {
          namespace_name = "axgjp2y2qkbb"
          bucket_name = "vault-backend"
          ha_enabled = "true"
          lock_bucket_name = "vault-backend-lock"
        }

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        service_registration "kubernetes" {}

  ui:
    enabled: true
  
  csi:
    enabled: true
  
  injector:
    enabled: false
