name: argocd
apiVersion: v2
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.27.5
    repository: https://argoproj.github.io/argo-helm
  - name: vault-secret-provider
    version: 1.0.0
    repository: file://../partial/vault-secret-provider
    condition: vault-secret-provider.enabled