vault-secret-provider:
  enabled: false

argo-cd:
  controller:
    metrics:
      serviceMonitor:
        enabled: false
  server:
    ingress:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false
  repoServer:
    metrics:
      serviceMonitor:
        enabled: false
  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false