k3s_nodes:
  children:
    masters:
      hosts:
        k3s0:
          ansible_host: 172.27.20.100
          description: 'NUC'
          mac: '00:23:24:d1:f3:f0'
        k3s1:
          ansible_host: 172.27.20.101
          description: 'ThinkCenter #1'
          mac: '00:23:24:d1:f4:d6'
        k3s2:
          ansible_host: 172.27.20.102
          description: 'ThinkCenter #2'
          mac: '00:23:24:e7:04:60'
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
