global:
  fullnameOverride: sonarr

networkPolicies:
  enabled: true

app-template:
  controller:
    replicas: 1
  image:
    repository: ghcr.io/onedr0p/sonarr-develop
    tag: 4.0.2.1408@sha256:f61a58b6075c16ad829eee55b94b99791e2b39c594080ecd21d2c6e0987ade53
  env:
    TZ: "Europe/Stockholm"
    SONARR__INSTANCE_NAME: Sonarr
    SONARR__PORT: 8989
    SONARR__APPLICATION_URL: "https://sonarr.siliconsheep.se"
    SONARR__LOG_LEVEL: info
  service:
    main:
      ports:
        http:
          port: 8989
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/auth-url: https://auth2.siliconsheep.se/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth2.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "sonarr.siliconsheep.se"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-siliconsheep-se
          hosts:
            - "sonarr.siliconsheep.se"
    api:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: "sonarr.siliconsheep.se"
          paths:
            - path: /api
              pathType: Prefix
      tls:
        - secretName: sonarr-siliconsheep-se
          hosts:
            - "sonarr.siliconsheep.se"
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        exec:
          command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
        failureThreshold: 5
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    media:
      enabled: true
      type: nfs
      server: "nas.siliconsheep.se"
      path: /volume1/media/
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 100
  resources:
    requests:
      cpu: 50m
      memory: 512M
    limits:
      memory: 1024M
