global:
  cluster: oke

traefik:
  globalArguments:
    - "--serverstransport.insecureskipverify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--providers.kubernetesingress.ingressendpoint.hostname=oke.traefik.siliconsheep.se"
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
  
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
  
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"