global:
  cluster: home

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=home.siiconsheep.se"
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
  
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "400m"