global:
  cluster: home

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=home.siliconsheep.se"

  providers:
    kubernetesIngress:
      publishedService:
        enabled: false

  autoscaling:
    minReplicas: 2
    maxReplicas: 5

  service:
    spec:
      loadBalancerIP: "172.27.120.2"
  
  resources:
    requests:
      cpu: "400m"
      memory: "50Mi"
    limits:
      cpu: "400m"
  
  ingressClass:
    enabled: true
    isDefaultClass: false