global:
  cluster: home

traefik:
  globalArguments:
    - "--serverstransport.insecureskipverify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--providers.kubernetesingress.ingressendpoint.hostname=home.traefik.siliconsheep.se"
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
  
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "400m"