global:
  cluster: home

traefik:
  # additionalArguments:
  #   - "--providers.kubernetesingress.ingressendpoint.hostname=home.siliconsheep.se"

  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
        pathOverride: "ingress/home-siliconsheep-se"

  autoscaling:
    minReplicas: 2
    maxReplicas: 5
  
  resources:
    requests:
      cpu: "400m"
      memory: "50Mi"
    limits:
      cpu: "400m"