version: "3"

services:
  dhcp:
    build:
      context: ./docker
      dockerfile: dhcp.Dockerfile
    volumes:
      - ./roles/pxe-server/files/data/pxe-config/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.local.conf:ro
    ports:
      - "67:67/udp"
  tftp:
    build:
      context: ./docker
      dockerfile: tftp.Dockerfile
    ports:
      - "69:69/udp"
    volumes:
      - ./roles/pxe-server/files/data/pxe-config/tftp:/var/lib/tftpboot:ro
  http:
    build:
      context: ./docker
      dockerfile: http.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./roles/pxe-server/files/data/iso:/usr/share/nginx/html/iso:ro
      - ./roles/pxe-server/files/data/pxe-config/http:/usr/share/nginx/html/files:ro
