vault-secret-provider:
  cluster: home
  enabled: true
  roleName: velero
  defaultObjectPath: infra/scaleway
  objects:  
  - name: cloud
    key: s3-credentials
  secretObjects: true
  secretName: velero-secret

velero:
  # AWS backend and CSI plugins configuration
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.7.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.5.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  # Velero Configuration
  configuration:
    backupStorageLocation:
    - name: scaleway-primary  
      provider: aws
      bucket: siliconsheep-velero-backups
      config:
        region: fr-par
        s3ForcePathStyle: true
        s3Url: https://s3.fr-par.scw.cloud

    volumeSnapshotLocation:
    - name: scaleway-primary  
      provider: aws
      config:
        region: fr-par

  credentials:
    existingSecret: velero-secret
  
  extraVolumeMounts:
  - name: secrets-fakemount
    mountPath: /mnt/secrets-fakemount
    readOnly: true

  extraVolumes:
  - name: secrets-fakemount
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: velero-home

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi