redis:
  image:
    repository: redis
    tag: 7.0.5
    pullPolicy: Always
  storageClassName: longhorn
  storageSize: 1Gi

vault-secret-provider:
  cluster: oke
  roleName: authentik
  objects:
  - path: auth/authentik
    name: postgres_user
  - path: auth/authentik
    name: postgres_password
  secretObjects: true
  secretName: authentik
