apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: argocd.argoproj.io/secret-type
              operator: In
              values:
              - cluster
            - key: k8s.siliconsheep.se/argo-app-suffix
              operator: Exists

  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: {{`'cluster-{{ normalize .name }}-app'`}}
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/kubernetes/charts/cluster-app'
    spec:
      project: default
      source:
        path: 'kubernetes/charts/cluster-app'
        targetRevision: HEAD
        repoURL: https://github.com/siliconsheep/homelab.git
        helm:
          values: |
            cluster: {{`'{{ .name }}'`}}
            clusterNormalized: {{`'{{ normalize .name }}'`}}
            argoAppSuffix: {{`'{{ index .metadata.labels "k8s.siliconsheep.se/argo-app-suffix" }}'`}}
      destination:
        namespace: argocd
        name: in-cluster
      syncPolicy:
        automated:
          prune: true