apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "wildcard-%s" (replace "." "-" .Values.global.domain) }}
spec:
  dnsNames:
    - {{ printf "*.%s" .Values.global.domain | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-production
  secretName: {{ printf "wildcard-%s" (replace "." "-" .Values.global.domain) }}

