# From Kubernetes v1.24 Secrets no longer get autocreated for service accounts,
# so we'll have to create one ourselves
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik-remote-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "authentik-remote-cluster.fullname" . }}
  labels:
    helm.sh/chart: {{ include "authentik-remote-cluster.chart" . }}
    app.kubernetes.io/name: {{ include "authentik-remote-cluster.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/service-account-token