name: prometheus
apiVersion: v2
version: 1.0.1
dependencies:
  - name: kube-prometheus-stack
    version: 67.11.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: vault-secret-provider
    version: 1.0.0
    repository: file://../partial/vault-secret-provider
    condition: vault-secret-provider.enabled