vault-secret-provider:
  enabled: true
  cluster: home
  roleName: grafana
  defaultObjectPath: auth/oauth-credentials/grafana
  objects:
    - name: client_id
    - name: client_secret
  secretObjects: true
  secretName: grafana-oauth

kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: auth-ak-outpost-home@kubernetescrd
      paths:
        - /
      hosts:
        - home.alertmanager.siliconsheep.se
      tls:
        - secretName: home-alertmanager-siliconsheep-se
          hosts:
            - home.alertmanager.siliconsheep.se

  kubeScheduler:
    service:
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeControllerManager:
    service:
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeEtcd:
    service:
      port: 2381
      targetPort: 2381
  prometheusOperator:
    admissionWebhooks:
      failurePolicy: Ignore
  prometheus:
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      hosts:
        - home.prometheus.siliconsheep.se
      paths:
        - /
      tls:
        - hosts: [home.prometheus.siliconsheep.se]
          secretName: home-prometheus-siliconsheep-se
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: auth-ak-outpost-home@kubernetescrd
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
  prometheus-node-exporter:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
  grafana:
    enabled: true
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.siliconsheep.se
      tls:
        - hosts:
            - grafana.siliconsheep.se
          secretName: grafana-siliconsheep-se
    persistence:
      enabled: false
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      server:
        root_url: https://grafana.siliconsheep.se
      auth.generic_oauth:
        name: authentik
        enabled: true
        scopes: openid email profile
        auth_url: https://auth.siliconsheep.se/application/o/authorize/
        token_url: https://auth.siliconsheep.se/application/o/token/
        api_url: https://auth.siliconsheep.se/application/o/userinfo/
        role_attribute_path: contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
      auth:
        oauth_auto_login: true
        signout_redirect_url: https://auth.siliconsheep.se/application/o/grafana/end-session/
    envFromSecret: grafana-oauth
    extraVolumeMounts:
      - name: secrets-fakemount
        mountPath: /mnt/secrets-fakemount
        readOnly: true
    extraContainerVolumes:
      - name: secrets-fakemount
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: prometheus-home


