vault-secret-provider:
  enabled: true
  cluster: home
  roleName: grafana
  defaultObjectPath: auth/grafana
  objects:
    - name: client-id
      secretName: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      path: auth/oauth-credentials/grafana
    - name: client-secret
      secretName: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      path: auth/oauth-credentials/grafana
    - name: oauth-scopes
      secretName: GF_AUTH_GENERIC_OAUTH_SCOPES
    - name: oauth-token-url
      secretName: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
    - name: oauth-auth-url
      secretName: GF_AUTH_GENERIC_OAUTH_AUTH_URL
    - name: oauth-api-url
      secretName: GF_AUTH_GENERIC_OAUTH_API_URL
    - name: signout-redirect-url
      secretName: GF_AUTH_SIGNOUT_REDIRECT_URL
  secretObjects: true
  secretName: grafana-oauth

kube-prometheus-stack:
  alertmanager:
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://auth2.siliconsheep.se/oauth2/auth?allowed_groups=admins
        nginx.ingress.kubernetes.io/auth-signin: https://auth2.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
      paths:
        - /
      hosts:
        - home.alertmanager.siliconsheep.se
      tls:
        - secretName: home-alertmanager-siliconsheep-se
          hosts:
            - home.alertmanager.siliconsheep.se
  coreDns:
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubeApiServer:
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubelet:
    serviceMonitor:
      cAdvisorRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
      probesRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubeScheduler:
    service:
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: true
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubeControllerManager:
    service:
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: true
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubeEtcd:
    service:
      port: 2381
      targetPort: 2381
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kubeProxy:
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  kube-state-metrics:
    prometheus:
      monitor:
        relabelings:
          - action: replace
            targetLabel: "cluster"
            replacement: "siliconsheep-home"
  
  prometheusOperator:
    admissionWebhooks:
      failurePolicy: Ignore
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
  
  prometheus:
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    serviceMonitor:
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: nginx
      hosts:
        - home.prometheus.siliconsheep.se
      paths:
        - /
      tls:
        - hosts: [home.prometheus.siliconsheep.se]
          secretName: home-prometheus-siliconsheep-se
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://auth2.siliconsheep.se/oauth2/auth?allowed_groups=admins
        nginx.ingress.kubernetes.io/auth-signin: https://auth2.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
        - job_name: 'federate'
          scrape_interval: 15s
          honor_labels: true
          metrics_path: '/federate'
          params:
            'match[]':
              - '{job=~".*"}'
          static_configs:
            - targets:
              - '172.28.0.133:9090'
  
  prometheus-node-exporter:
    prometheus:
      monitor:
        relabelings:
          - action: replace
            targetLabel: "cluster"
            replacement: "siliconsheep-home"
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      
  grafana:
    enabled: true
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: true
      relabelings:
        - action: replace
          targetLabel: "cluster"
          replacement: "siliconsheep-home"
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.siliconsheep.se
      tls:
        - hosts:
            - grafana.siliconsheep.se
          secretName: grafana-siliconsheep-se
    persistence:
      enabled: false
    grafana.ini:
      server:
        root_url: https://grafana.siliconsheep.se
      auth.generic_oauth:
        name: Auth0
        enabled: true
        role_attribute_path: contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
      auth:
        oauth_auto_login: true
    envFromSecret: grafana-oauth
    extraSecretMounts:
      - name: secrets-fakemount
        mountPath: /mnt/secrets-fakemount
        readOnly: true
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: prometheus-home


