kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: auth-ak-outpost-test-provider@kubernetescrd
      paths:
        - /
      hosts:
        - oke.alertmanager.siliconsheep.se
      tls:
        - secretName: oke-alertmanager-siliconsheep-se
          hosts:
            - oke.alertmanager.siliconsheep.se

  prometheus:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: auth-ak-outpost-test-provider@kubernetescrd
      hosts:
        - oke.prometheus.siliconsheep.se
      paths:
        - /
      tls:
        - secretName: oke-prometheus-siliconsheep-se
          hosts:
            - oke.prometheus.siliconsheep.se

  grafana:
    enabled: false
