apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-secret-mounter
  labels:
    app: longhorn-secret-mounter
    app.kubernetes.io/name: longhorn-secret-mounter
    app.kubernetes.io/managed-by: {{  .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  namespace: {{ .Release.Namespace }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: longhorn-secret-mounter
    template:
      metadata:
        labels:
          app: longhorn-secret-mounter
          app.kubernetes.io/name: longhorn-secret-mounter
          app.kubernetes.io/managed-by: {{  .Release.Service }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/version: {{ .Chart.AppVersion }}
          helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      spec:
        containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          volumeMounts:
            - mountPath: /mnt/secrets-fakemount
              name: secrets-fakemount
              readOnly: true
        serviceAccountName: longhorn-service-account
        volumes:
        - name: secrets-fakemount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: longhorn-home
          
        