apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-disk-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: longhorn-disk-config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
