apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-{{ .Values.clusterNormalized }}
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/siliconsheep/homelab.git
        revision: HEAD
        files:
          - path: "kubernetes/clusters/{{ .Values.clusterNormalized }}.yaml"
      selector:
        matchExpressions:
          - key: rawHelm
            operator: NotIn
            values:
              - "true"
              - "yes"
              - "1"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ printf "{{ .name }}-%s" .Values.argoAppSuffix }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: {{`'/kubernetes/charts/{{or (index . "chartPath") .name }}'`}}
    spec:
      project: default
      source:
        path: {{`'kubernetes/charts/{{or (index . "chartPath") .name }}'`}}
        targetRevision: HEAD
        repoURL: https://github.com/siliconsheep/homelab.git
        # For now, something like below doesn't work, go templating
        # in ApplicationSets is per (string) field :/
        #
        # {{`{{- if .valueFiles }}`}}
        # helm:
        #   valueFiles:
        #   {{`{{- range .valueFiles }}`}}
        #     - {{`{{ . }}`}}
        #   {{`{{- end }}`}}
        # {{`{{- end }}`}}
        #
        # So this (ugly) hack allows up to pick up to 10 value files
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            {{- range until 10 }}
            - '{{ printf "{{ if gt (len .valueFiles) %d }}{{ index .valueFiles %d }}{{ else }}../empty.yaml{{ end }}" . . }}'
            {{- end }}
      destination:
        namespace: {{`'{{or (index . "namespace") .name }}'`}}
        name: '{{ .Values.clusterNormalized }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        retry:
          limit: 3
          backoff:
            duration: 1m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply={{`{{or (index . "serverSideApply") "false" }}`}}
      ignoreDifferences:
        - group: monitoring.coreos.com
          kind: ServiceMonitor
          name: kube-prometheus-stack-kubelet
          jqPathExpressions:
          - .spec.endpoints[]?.relabelings[]?.action