apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-{{ .Values.clusterNormalized }}
spec:
  generators:
    - git:
        repoURL: https://github.com/siliconsheep/homelab.git
        revision: HEAD
        files:
          - path: "kubernetes/clusters/{{ .Values.clusterNormalized }}.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: {{`'{{ .name }}'`}}
      annotations:
        argocd.argoproj.io/manifest-generate-paths: {{`'/kubernetes/charts/{{or (index . "chartPath") .name }}'`}}
    spec:
      project: default
      source:
        path: {{`'kubernetes/charts/{{or (index . "chartPath") .name }}'`}}
        targetRevision: HEAD
        repoURL: https://github.com/siliconsheep/homelab.git
        {{`'{{- if .valueFiles }}'`}}
        helm:
          valueFiles:
          {{`'{{- range .valueFiles }}'`}}
            - {{`'{{ . }}'`}}
          {{`'{{- end }}'`}}
        {{`'{{- end }}'`}}
      destination:
        namespace: {{`'{{or (index . "namespace") .name }}'`}}
        name: '{{ .Values.clusterNormalized }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true