# From Kubernetes v1.24 Secrets no longer get autocreated for service accounts,
# so we'll have to create one ourselves
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-secret.serviceAccount.name" . }}-service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "vault-secret.serviceAccount.name" . }}
  labels:
    helm.sh/chart: {{ include "vault-secret.chart" . }}
    app.kubernetes.io/name: {{ include "vault-secret.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/service-account-token