apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helm-raw
spec:
  init:
    command: ["sh", "-c"]
    args: ["helm dependency build"]
  generate:
    command: ["sh", "-c"]
    args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_helm_args} . --include-crds"]
