vault-secret-provider:
  enabled: false

cert-manager:
  fullnameOverride: cert-manager
  installCRDs: true

  resources:
    requests:
      cpu: 35m
      memory: 125Mi
    limits:
      memory: 125Mi

  webhook:
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        memory: 100Mi

  cainjector:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 35m
        memory: 250Mi
      limits:
        memory: 250Mi