name: cert-manager
apiVersion: v2
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.18.2
    repository: https://charts.jetstack.io
  - name: vault-secret-provider
    version: 1.0.0
    repository: file://../partial/vault-secret-provider
    condition: vault-secret-provider.enabled
