---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "siliconsheep-se"
  namespace: ingress
spec:
  secretName: "siliconsheep-se-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "siliconsheep.se"
  dnsNames:
    - "siliconsheep.se"
    - "*.siliconsheep.se"