{{- if eq .Values.global.cluster "home" }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-expose
  namespace: ingress
spec:
  type: ExternalName
  externalName: home.siliconsheep.se
{{- end }}
