global:
  fullnameOverride: sabnzbd

app-template:
  image:
    repository: ghcr.io/onedr0p/sabnzbd
    tag: 4.0.1@sha256:3d24a7e4219f2d362a530edb2e5c1df73dfec01fcae38a7400e216453900c2ae
  env:
    TZ: "Europe/Stockholm"
    SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd,sabnzbd.siliconsheep.se
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: auth-ak-outpost-home@kubernetescrd
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "sabnzbd.siliconsheep.se"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sabnzbd-siliconsheep-se
          hosts:
            - "sabnzbd.siliconsheep.se"
  securityContext:
    seLinuxOptions:
      level: s0
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 100
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    media:
      enabled: true
      type: nfs
      server: "nas.siliconsheep.se"
      path: /volume1/media/
      mountPath: /media
  resources:
    requests:
      memory: 500Mi
      cpu: 300m
    limits:
      memory: 1500Mi
      cpu: 1000m