FROM ubuntu:20.04
LABEL maintainer="dieter.bocklandt@gmail.com"

RUN apt-get update && apt-get install -y \
        ansible \
        ansible-lint \
        git \
        make \
        python-netaddr \
        iproute2 \
        xorriso