global:
  fullnameOverride: node-feature-discovery

node-feature-discovery:
  master:
    tolerations: []
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution: []

  worker:
    config:
      core:
        sources:
          - custom
          - pci
          - usb
      sources:
        usb:
          deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
          deviceLabelFields:
            - class
            - vendor
            - device
        custom:
          - name: intel-gpu
            matchOn:
              - pciId:
                  class: ["0300"]
                  vendor: ["8086"]
          - name: coral-tpu
            matchOn:
              - pciId:
                  class: ["0880"]
                  vendor: ["1ac1"]
                  device: ["089a"]
          - name: zwave
            matchOn:
              - usbId:
                  class: ["02"]
                  vendor: ["0658"]
                  device: ["0200"]
          - name: ups-apc
            matchOn:
              - usbId:
                  class: ["03"]
                  vendor: ["051d"]
                  device: ["0002"]
    tolerations:
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"