metrics-server:
  fullnameOverride: metrics-server

  serviceAccount:
    create: true
  
  rbac:
    create: true

  apiService:
    create: true

  extraArgs:
    kubelet-preferred-address-types: InternalIP
    kubelet-insecure-tls: true
