global:
  fullnameOverride: intel-gpu-plugin

app-template:
  controller:
    type: daemonset
    strategy: RollingUpdate
  
  image:
    repository: docker.io/intel/intel-gpu-plugin
    tag: 0.28.0
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: feature.node.kubernetes.io/custom-intel-gpu
                operator: In
                values:
                  - "true"
  args:
    - -shared-dev-num
    - "5"

  service:
    main:
      enabled: false

  ingress:
    main:
      enabled: false
  
  persistence:
    devfs:
      enabled: true
      type: hostPath
      hostPath: /dev/dri
      hostPathType: Directory
      readOnly: true
    sysfs:
      enabled: true
      type: hostPath
      hostPath: /sys/class/drm
      hostPathType: Directory
      readOnly: true
    kubeletsockets:
      enabled: true
      type: hostPath
      hostPathType: Directory
      hostPath: /var/lib/kubelet/device-plugins
  
  # TODO(intel-gpu-plugin): Write probes to check for something to tell if it's working
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
    startup:
      enabled: false

  resources:
    requests:
      cpu: 15m
      memory: 64M
    limits:
      memory: 64M