vault-secret-provider:
  cluster: oke
  enabled: false

diskConfig:
  - name: iscsi-disk
    path: /data
    allowScheduling: true
    storageReserved: 536870912
    tags:
      - iscsi
      - balanced

longhorn:
  persistence:
    defaultClassReplicaCount: 3