diskConfig:
  - name: nvme-disk
    path: /data
    allowScheduling: true
    storageReserved: 536870912
    tags:
      - nvme
      - fast

longhorn:
  persistence:
    defaultClassReplicaCount: 2 # Only have 2 nodes to play with here :/