vault-secret-provider:
  cluster: home
  enabled: true
  roleName: longhorn
  defaultObjectPath: infra/scaleway
  objects:  
  - name: AWS_ACCESS_KEY_ID
    key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    key: aws-secret-access-key
  - name: AWS_REGION
    key: aws-region
  - name: AWS_ENDPOINTS
    key: aws-endpoints
  secretObjects: true
  secretName: scw-credentials

diskConfig:
  - name: nvme-disk
    path: /data
    allowScheduling: true
    storageReserved: 536870912
    tags:
      - nvme
      - fast

longhorn:
  defaultSettings:
    backupTarget: s3://siliconsheep-longhorn@fr-par
    backupTargetCredentialSecret: scw-credentials

  persistence:
    defaultClassReplicaCount: 2 # Only have 2 nodes to play with here :/

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/auth-url: https://auth2.siliconsheep.se/oauth2/auth?allowed_groups=admins
      nginx.ingress.kubernetes.io/auth-signin: https://auth2.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: "longhorn.siliconsheep.se"
    tls: true
    tlsSecret: longhorn-siliconsheep-se