networkPolicies:
  enabled: false

app-template:
  image:
    repository: ghcr.io/mendhak/http-https-echo
    tag: "30"

  env:
    HTTP_PORT: 8080
    LOG_WITHOUT_NEWLINE: "true"
    LOG_IGNORE_PATH: "/healthz"

  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"

  resources:
    requests:
      cpu: 5m
      memory: 30M
    limits:
      memory: 30M
