app-template:
  ingress:
    main:
      annotations:
        nginx.ingress.kubernetes.io/auth-url: https://auth.siliconsheep.se/oauth2/auth?allowed_groups=admins
        nginx.ingress.kubernetes.io/auth-signin: https://auth.siliconsheep.se/oauth2/start?rd=$scheme://$best_http_host$request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "oke.echo.siliconsheep.se"
          paths:
            - path: /
      tls:
        - hosts: [oke.echo.siliconsheep.se]
          secretName: oke-echo-siliconsheep-se