apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: {{ .Release.Name }}-bfd-profile
  namespace: {{ .Release.namespace }}
spec:
  echoMode: true
  minimumTtl: 253
  receiveInterval: 300
  transmitInterval: 300
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ .Release.Name }}-bgp-peer
  namespace: {{ .Release.namespace }}
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 172.27.20.1
  bfdProfile: {{ .Release.Name }}-bfd-profile
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ .Release.Name }}-bgp-advertisement
  namespace: {{ .Release.namespace }}
spec:
  ipAddressPools:
  - {{ .Release.Name }}-peer